# Generated by Django 5.1.1 on 2024-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_boat_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
