# Generated by Django 5.1.1 on 2024-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_boat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='ce_rating',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('vrijgesteld', 'Vrijgesteld')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='construction_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='crm_registration_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='deck_construction',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='deck_finish',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='deck_material',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('benzine', 'Benzine'), ('elektrisch', 'Elektrisch'), ('waterstof', 'Waterstof'), ('overig', 'Overig')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='glazing',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='hull_material',
            field=models.CharField(blank=True, choices=[('aluminium', 'Aluminium'), ('composiet', 'Composiet'), ('ferro_cement', 'Ferro cement'), ('hout', 'Hout'), ('polyester', 'Polyester'), ('pvc', 'PVC'), ('staal', 'Staal'), ('anders', 'Anders')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='mast_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='merk',
            field=models.CharField(blank=True, choices=[('breedendam', 'Breedendam'), ('de_vries_len', 'De Vries Len'), ('grand_banks', 'Grand Banks'), ('linssen', 'Linssen'), ('mulder', 'Mulder'), ('sealine', 'Sealine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='model',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='model_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='motor_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='propulsion',
            field=models.CharField(blank=True, choices=[('stern_drive', 'Stern-drive'), ('sail_drive', 'Sail-drive'), ('v_drive', 'V-drive'), ('jet_drive', 'Jet-drive'), ('shaft_drive', 'Shaft-drive'), ('surface_drive', 'Surface-drive'), ('pod_drive', 'Pod-drive'), ('overig', 'Overig')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='registered_in_land_registry',
            field=models.CharField(blank=True, choices=[('ja', 'Ja'), ('nee', 'Nee')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('latent', 'Latent'), ('actief', 'Actief')], default='latent', max_length=10),
        ),
        migrations.AddField(
            model_name='boat',
            name='vat_status',
            field=models.CharField(blank=True, choices=[('BTW betaald', 'BTW betaald'), ('BTW niet betaald', 'BTW niet betaald'), ('BTW vrijgesteld', 'BTW vrijgesteld'), ('BTW onbekend', 'BTW onbekend')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='water_displacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='werf',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='win_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='yacht_category',
            field=models.CharField(blank=True, choices=[('elektrisch_jacht', 'Elektrisch Jacht'), ('motor_jacht', 'Motor Jacht'), ('zeil_jacht', 'Zeil Jacht'), ('overig', 'Overig')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='yacht_type',
            field=models.CharField(choices=[('motor', 'Motor jacht'), ('zeil', 'Zeil jacht'), ('elektrisch', 'Elektrisch jacht')], default='motor', max_length=20),
        ),
    ]
