# Generated by Django 5.1.1 on 2024-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_boat_construction_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='mast_details',
            new_name='ac_system',
        ),
        migrations.AddField(
            model_name='boat',
            name='air_conditioning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='ais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='anchor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='auto_pilot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bathing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='battery_charger',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bezaan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bilge_pump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bimini',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='black_water_pump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='black_water_tank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bold_battery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bow_thruster',
            field=models.CharField(blank=True, choices=[('ja', 'Ja'), ('nee', 'Nee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bow_thruster_battery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cabins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='compass',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cooker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cooling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='boat',
            name='cruising_speed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cudly_tube',
            field=models.CharField(blank=True, choices=[('ja', 'Ja'), ('nee', 'Nee')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='dc_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='depth_gauge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='dinghy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='dishwasher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='double_beds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='drinking_water_tank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='dryer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='emergency_engine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='engine_room_extinguishing_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='epirb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='extra_steering_position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fence_screw',
            field=models.CharField(blank=True, choices=[('ja', 'Ja'), ('nee', 'Nee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fenders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='filling_in_liters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fire_alarm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fire_extinguisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='freezer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fridge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fuel_tank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gallery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='boat',
            name='gangway',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gas_alarm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gearbox',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='generator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='generator_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='genoa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='genoa_reef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gps_plotter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='grey_water_pump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='grey_water_tank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='heating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='height_of_mast_windshield_down',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='high_water_alarm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='home_batteries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='hot_water_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='ice_cubes_machine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='interior_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='inverter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='liating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='lifeboat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='liter_ph_ks',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='liter_ph_ms',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='loa',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='lwl',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='mainsail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='masts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='maximum_speed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='microwave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='mob_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='motor_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='number_of_sails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='operating_hours',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='oven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='propeller_shaft_lubrication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='propellor_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='radar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='radar_detector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='radar_screen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='sail_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='search_light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='showers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='single_beds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='speedometer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='spinal_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='stabilizers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='start_up_batteries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='steering_position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='stir_mounted_pointer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='storm_breeding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='toilets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='trim_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='trisail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='tube_cap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='verstaging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='vhf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='washbasin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='washing_machine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='water_maker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='water_pressure_pump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='wind_gauge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='wine_fridge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
