# Generated by Django 5.1.1 on 2024-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_customer_address_customer_email_customer_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_business',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='btw_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='from_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_business',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_option',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='option_list',
            field=models.CharField(blank=True, choices=[('latent', 'Latent'), ('potentiele_opdrachtgever', 'Potentiele-Opdrachtgever'), ('opdrachtgever', 'Opdrachtgever'), ('verkoper', 'Verkoper'), ('opzoek', 'Opzoek'), ('urgent', 'Urgent')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
