# Generated by Django 5.1.1 on 2024-10-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_boat_condition_alter_boat_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
